"""Integration Tests for Multi-Strategy Support"""
import pytest
from pathlib import Path
import sys

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

from src.engines import BacktestEngine
from src.config import load_config


class TestMultiStrategy:
    """Test multi-strategy functionality"""

    def test_config_loading(self):
        """Test that multi-strategy config is loaded correctly"""
        config_path = Path(__file__).parent.parent.parent / "config" / "e2e.yaml"
        config = load_config(str(config_path))

        # Verify structure
        assert 'strategies' in config
        assert len(config['strategies']) == 2

        # Verify strategy configs
        assert config['strategies'][0]['name'] == 'ma_main'
        assert config['strategies'][0]['enabled'] == True
        assert config['strategies'][0]['class'] == 'MovingAverageStrategy'

        assert config['strategies'][1]['name'] == 'test_buy_every_bar'
        assert config['strategies'][1]['enabled'] == False
        assert config['strategies'][1]['class'] == 'BuyEveryBarStrategy'

    def test_strategy_loading(self):
        """Test that only enabled strategies are loaded"""
        config_path = Path(__file__).parent.parent.parent / "config" / "e2e.yaml"

        # Check if data file exists, skip if not
        config = load_config(str(config_path))
        parquet_path = Path(config['parquet_path'])
        symbol_file = parquet_path / f"{config['symbols'][0]}_2024.parquet"

        if not symbol_file.exists():
            pytest.skip(f"Test data not found: {symbol_file}")

        engine = BacktestEngine(str(config_path))

        # Should load 1 strategy (ma_main, not test_buy_every_bar)
        assert len(engine.strategies) == 1

        # Verify strategy names
        strategy_names = [s.name for s in engine.strategies]
        assert 'ma_main' in strategy_names
        assert 'test_buy_every_bar' not in strategy_names

        # Verify each strategy has its own config
        for strategy in engine.strategies:
            assert strategy.name in ['ma_main']
            assert strategy.symbols == ['600000.SH']
            assert strategy.params is not None

    def test_strategy_signals_have_strategy_id(self):
        """Test that signals generated by strategies include strategy_id"""
        from src.strategies import MovingAverageStrategy
        from src.data import BarData
        from datetime import datetime

        # Create a strategy
        strategy = MovingAverageStrategy(
            name='test_strategy',
            symbols=['000001.SZ'],
            params={'ema_period': 10, 'buy_threshold': -0.005}
        )

        # Create a test bar
        bar = BarData(
            symbol='000001.SZ',
            timestamp=datetime.now(),
            open=10.0,
            high=10.5,
            low=9.5,
            close=10.0,
            volume=1000000
        )

        # Process enough bars to trigger signals (need at least ema_period bars)
        for i in range(15):
            # Create bars that will trigger buy signal
            if i < 10:
                # First 10 bars: normal price
                test_bar = BarData(
                    symbol='000001.SZ',
                    timestamp=datetime.now(),
                    open=10.0,
                    high=10.1,
                    low=9.9,
                    close=10.0,
                    volume=1000000
                )
            else:
                # Next bars: price drops to trigger buy
                test_bar = BarData(
                    symbol='000001.SZ',
                    timestamp=datetime.now(),
                    open=9.8,
                    high=9.9,
                    low=9.5,
                    close=9.5,  # Below EMA
                    volume=1000000
                )

            signals = strategy.on_bar(test_bar)
            if signals:
                # Verify signals have strategy_id
                for signal in signals:
                    assert signal.strategy_id == 'test_strategy'
                    assert hasattr(signal, 'strategy_id')
                break

    def test_strategy_isolation(self):
        """Test that strategies maintain independent positions"""
        from src.strategies import MovingAverageStrategy
        from src.execution import Position

        # Create two strategies
        strategy1 = MovingAverageStrategy(
            name='strategy1',
            symbols=['000001.SZ'],
            params={'ema_period': 10}
        )

        strategy2 = MovingAverageStrategy(
            name='strategy2',
            symbols=['000001.SZ'],
            params={'ema_period': 10}
        )

        # They should have independent position dicts (different objects)
        assert strategy1.positions is not strategy2.positions
        assert len(strategy1.positions) == 0
        assert len(strategy2.positions) == 0

        # Add position to strategy1
        strategy1.positions['000001.SZ'] = Position('000001.SZ')
        strategy1.positions['000001.SZ'].add(100, 10.0)

        # Verify isolation
        assert strategy1.positions['000001.SZ'].quantity == 100
        assert len(strategy2.positions) == 0  # strategy2 still empty

    def test_backward_compatibility_single_strategy(self):
        """Test that old single-strategy config format still works"""
        # Create a temporary old-style config
        config_path = Path(__file__).parent.parent.parent / "config" / "test_old_format.yaml"

        old_config = """
mode: research
parquet_path: ../data/parquet
symbols:
  - 000001.SZ
start_date: 20240101
end_date: 20240110
strategy: moving_average
strategy_params:
  ema_period: 10
  buy_threshold: -0.005
initial_capital: 1000000
commission_rate: 0.0003
"""
        config_path.write_text(old_config)

        try:
            # Check if data file exists
            parquet_path = Path("../data/parquet")
            symbol_file = parquet_path / "000001.SZ_2024.parquet"

            if not symbol_file.exists():
                pytest.skip(f"Test data not found: {symbol_file}")

            engine = BacktestEngine(str(config_path))

            # Should load 1 strategy with default name
            assert len(engine.strategies) == 1
            assert engine.strategies[0].name == 'moving_average'
        finally:
            # Clean up
            if config_path.exists():
                config_path.unlink()


if __name__ == "__main__":
    # Run tests
    pytest.main([__file__, "-v"])
