apiVersion: v1
kind: Service
metadata:
  name: execution-service
  namespace: trading-platform
  labels:
    app: execution-service
    version: v1
spec:
  type: NodePort
  selector:
    app: execution-service
  ports:
    - name: grpc
      port: 8084
      targetPort: 8084
      nodePort: 30884
      protocol: TCP
  sessionAffinity: None
