namespace ExecutionService.Models;

public enum OrderSide
{
    Buy,
    Sell
}

public enum OrderStatus
{
    Pending,
    Filled,
    Partial,
    Cancelled,
    Rejected,
    Expired    // P2.3 added: DAY order not filled by market close
}

/// <summary>
/// Time-in-Force (added in P2.1)
/// </summary>
public enum TimeInForce
{
    /// <summary>Valid for the day (default for A-shares)</summary>
    Day = 0,

    /// <summary>Immediate-Or-Cancel (supported for STAR Market/ChiNext market orders)</summary>
    IOC = 1,

    /// <summary>Good-Till-Cancel (not supported for A-shares; reserved for US stocks/futures)</summary>
    GTC = 2,

    /// <summary>Fill-Or-Kill (not supported for A-shares; reserved)</summary>
    FOK = 3
}

public enum OrderType
{
    Market,
    Limit,
    Stop,
    StopLimit
}

public class Order
{
    // Database primary key (auto-generated by database)
    public long Id { get; set; }

    // Business order ID for external references
    public string OrderId { get; set; } = Guid.NewGuid().ToString();
    public string SessionId { get; set; } = string.Empty;
    public string Symbol { get; set; } = string.Empty;
    public OrderSide Side { get; set; }
    public OrderType OrderType { get; set; } = OrderType.Market;
    public decimal Quantity { get; set; }
    public decimal Price { get; set; }
    public decimal StopPrice { get; set; }
    public OrderStatus Status { get; set; } = OrderStatus.Pending;
    public decimal FillPrice { get; set; }
    public decimal FilledQuantity { get; set; }
    public decimal Commission { get; set; }
    public string SignalId { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? FilledAt { get; set; }
    public string StrategyId { get; set; } = string.Empty;
    public string Reason { get; set; } = string.Empty; // Rejection reason
    public ExecutionMode ExecutionMode { get; set; } = ExecutionMode.SIMULATION; // Execution mode

    // P2.1 added
    public TimeInForce TimeInForce { get; set; } = TimeInForce.Day;

    // P0.3 added: nullable field, expected expiration time for DAY orders
    public DateTime? ExpireAt { get; set; }

    // P0.3 added: remaining unfilled quantity (persisted to a column, synced by PositionManager before saving:
    //   order.RemainingQuantity = order.Quantity - order.FilledQuantity)
    public decimal RemainingQuantity { get; set; }
}
