# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import execution_pb2 as execution__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutionStub(object):
    """Execution service interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOrder = channel.unary_unary(
                '/execution.Execution/SubmitOrder',
                request_serializer=execution__pb2.OrderRequest.SerializeToString,
                response_deserializer=execution__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/execution.Execution/CancelOrder',
                request_serializer=execution__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=execution__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/execution.Execution/GetOrderStatus',
                request_serializer=execution__pb2.OrderStatusRequest.SerializeToString,
                response_deserializer=execution__pb2.OrderStatusResponse.FromString,
                _registered_method=True)
        self.GetPosition = channel.unary_unary(
                '/execution.Execution/GetPosition',
                request_serializer=execution__pb2.PositionRequest.SerializeToString,
                response_deserializer=execution__pb2.PositionResponse.FromString,
                _registered_method=True)
        self.GetAllPositions = channel.unary_unary(
                '/execution.Execution/GetAllPositions',
                request_serializer=execution__pb2.AllPositionsRequest.SerializeToString,
                response_deserializer=execution__pb2.AllPositionsResponse.FromString,
                _registered_method=True)
        self.GetAccount = channel.unary_unary(
                '/execution.Execution/GetAccount',
                request_serializer=execution__pb2.AccountRequest.SerializeToString,
                response_deserializer=execution__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.SubscribePnLUpdates = channel.unary_stream(
                '/execution.Execution/SubscribePnLUpdates',
                request_serializer=execution__pb2.PnLSubscribeRequest.SerializeToString,
                response_deserializer=execution__pb2.PnLUpdate.FromString,
                _registered_method=True)
        self.SubscribeOrderUpdates = channel.unary_stream(
                '/execution.Execution/SubscribeOrderUpdates',
                request_serializer=execution__pb2.OrderUpdatesSubscribeRequest.SerializeToString,
                response_deserializer=execution__pb2.OrderUpdate.FromString,
                _registered_method=True)
        self.ExpireDayOrders = channel.unary_unary(
                '/execution.Execution/ExpireDayOrders',
                request_serializer=execution__pb2.ExpireDayOrdersRequest.SerializeToString,
                response_deserializer=execution__pb2.ExpireDayOrdersResponse.FromString,
                _registered_method=True)


class ExecutionServicer(object):
    """Execution service interface
    """

    def SubmitOrder(self, request, context):
        """Submit a single order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Cancel order (added in P0.2)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """Query order status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """Query a single position
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllPositions(self, request, context):
        """Query all positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """Query account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribePnLUpdates(self, request, context):
        """Subscribe to PnL updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeOrderUpdates(self, request, context):
        """Subscribe to order status updates (added in P1.2)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpireDayOrders(self, request, context):
        """Market close cancel: mark Pending/Partial DAY orders as Expired (added in P2.2)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=execution__pb2.OrderRequest.FromString,
                    response_serializer=execution__pb2.OrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=execution__pb2.CancelOrderRequest.FromString,
                    response_serializer=execution__pb2.CancelOrderResponse.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=execution__pb2.OrderStatusRequest.FromString,
                    response_serializer=execution__pb2.OrderStatusResponse.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=execution__pb2.PositionRequest.FromString,
                    response_serializer=execution__pb2.PositionResponse.SerializeToString,
            ),
            'GetAllPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPositions,
                    request_deserializer=execution__pb2.AllPositionsRequest.FromString,
                    response_serializer=execution__pb2.AllPositionsResponse.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=execution__pb2.AccountRequest.FromString,
                    response_serializer=execution__pb2.AccountResponse.SerializeToString,
            ),
            'SubscribePnLUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribePnLUpdates,
                    request_deserializer=execution__pb2.PnLSubscribeRequest.FromString,
                    response_serializer=execution__pb2.PnLUpdate.SerializeToString,
            ),
            'SubscribeOrderUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeOrderUpdates,
                    request_deserializer=execution__pb2.OrderUpdatesSubscribeRequest.FromString,
                    response_serializer=execution__pb2.OrderUpdate.SerializeToString,
            ),
            'ExpireDayOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpireDayOrders,
                    request_deserializer=execution__pb2.ExpireDayOrdersRequest.FromString,
                    response_serializer=execution__pb2.ExpireDayOrdersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'execution.Execution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('execution.Execution', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Execution(object):
    """Execution service interface
    """

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.Execution/SubmitOrder',
            execution__pb2.OrderRequest.SerializeToString,
            execution__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.Execution/CancelOrder',
            execution__pb2.CancelOrderRequest.SerializeToString,
            execution__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.Execution/GetOrderStatus',
            execution__pb2.OrderStatusRequest.SerializeToString,
            execution__pb2.OrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.Execution/GetPosition',
            execution__pb2.PositionRequest.SerializeToString,
            execution__pb2.PositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.Execution/GetAllPositions',
            execution__pb2.AllPositionsRequest.SerializeToString,
            execution__pb2.AllPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.Execution/GetAccount',
            execution__pb2.AccountRequest.SerializeToString,
            execution__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribePnLUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/execution.Execution/SubscribePnLUpdates',
            execution__pb2.PnLSubscribeRequest.SerializeToString,
            execution__pb2.PnLUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeOrderUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/execution.Execution/SubscribeOrderUpdates',
            execution__pb2.OrderUpdatesSubscribeRequest.SerializeToString,
            execution__pb2.OrderUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpireDayOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.Execution/ExpireDayOrders',
            execution__pb2.ExpireDayOrdersRequest.SerializeToString,
            execution__pb2.ExpireDayOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
