# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gm_trading_pb2 as gm__trading__pb2


class GMTradingStub(object):
    """GM trading service interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/gmtrading.GMTrading/PlaceOrder',
                request_serializer=gm__trading__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=gm__trading__pb2.PlaceOrderResponse.FromString,
                )
        self.CancelOrder = channel.unary_unary(
                '/gmtrading.GMTrading/CancelOrder',
                request_serializer=gm__trading__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=gm__trading__pb2.CancelOrderResponse.FromString,
                )
        self.GetCash = channel.unary_unary(
                '/gmtrading.GMTrading/GetCash',
                request_serializer=gm__trading__pb2.GetCashRequest.SerializeToString,
                response_deserializer=gm__trading__pb2.GetCashResponse.FromString,
                )
        self.GetPosition = channel.unary_unary(
                '/gmtrading.GMTrading/GetPosition',
                request_serializer=gm__trading__pb2.GetPositionRequest.SerializeToString,
                response_deserializer=gm__trading__pb2.GetPositionResponse.FromString,
                )
        self.GetOrders = channel.unary_unary(
                '/gmtrading.GMTrading/GetOrders',
                request_serializer=gm__trading__pb2.GetOrdersRequest.SerializeToString,
                response_deserializer=gm__trading__pb2.GetOrdersResponse.FromString,
                )


class GMTradingServicer(object):
    """GM trading service interface
    """

    def PlaceOrder(self, request, context):
        """Place order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Cancel order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCash(self, request, context):
        """Query account cash
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """Query position
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Query orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GMTradingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=gm__trading__pb2.PlaceOrderRequest.FromString,
                    response_serializer=gm__trading__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=gm__trading__pb2.CancelOrderRequest.FromString,
                    response_serializer=gm__trading__pb2.CancelOrderResponse.SerializeToString,
            ),
            'GetCash': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCash,
                    request_deserializer=gm__trading__pb2.GetCashRequest.FromString,
                    response_serializer=gm__trading__pb2.GetCashResponse.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=gm__trading__pb2.GetPositionRequest.FromString,
                    response_serializer=gm__trading__pb2.GetPositionResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=gm__trading__pb2.GetOrdersRequest.FromString,
                    response_serializer=gm__trading__pb2.GetOrdersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gmtrading.GMTrading', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GMTrading(object):
    """GM trading service interface
    """

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmtrading.GMTrading/PlaceOrder',
            gm__trading__pb2.PlaceOrderRequest.SerializeToString,
            gm__trading__pb2.PlaceOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmtrading.GMTrading/CancelOrder',
            gm__trading__pb2.CancelOrderRequest.SerializeToString,
            gm__trading__pb2.CancelOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmtrading.GMTrading/GetCash',
            gm__trading__pb2.GetCashRequest.SerializeToString,
            gm__trading__pb2.GetCashResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmtrading.GMTrading/GetPosition',
            gm__trading__pb2.GetPositionRequest.SerializeToString,
            gm__trading__pb2.GetPositionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmtrading.GMTrading/GetOrders',
            gm__trading__pb2.GetOrdersRequest.SerializeToString,
            gm__trading__pb2.GetOrdersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
